var goodData={
    path:[
        {
            title:"手机、数码、通讯",
            url:"###"
        },
        {
            title:"手机",
            url:"###"
        },
        {
            title:"Apple苹果",
            url:"###"
        },{
            title:"iphone 6S系"
        }
    ],
    imagessrc:[
        {b:"./images/b1.jpg",s:"./images/s1.jpg"},
        {b:"./images/b2.jpg",s:"./images/s2.jpg"},
        {b:"./images/b3.jpg",s:"./images/s3.jpg"},
        {b:"./images/b1.jpg",s:"./images/s1.jpg"},
        {b:"./images/b2.jpg",s:"./images/s2.jpg"},
        {b:"./images/b3.jpg",s:"./images/s3.jpg"},
        {b:"./images/b1.jpg",s:"./images/s1.jpg"},
        {b:"./images/b2.jpg",s:"./images/s2.jpg"},
        {b:"./images/b3.jpg",s:"./images/s3.jpg"},
    ],
    goodsDetail:{
        title:"Apple iPhone 6s (A1700) 64G玫瑰金色 移动",
        recommend:"推荐选择下方[移动优惠购]，手机套餐",
        price:5999,
        promoteSales:{
            type:"加价购",
            content:"满999.99另加20.00元，或满1999.00"
        },
        support:"以旧换新，限制手机回收 4G套餐超值抢",
        address:"广东省 深圳市 宝安区",
        evaluateNum: 670000,
        crumbData:[
            {
                "title":"选择颜色",
                "data":[
                    {
                        type:"金色",
                        changePrice:0
                    },
                    {
                        type:"银色",
                        changePrice:40
                    },
                    {
                        type:"黄色",
                        changePrice:60
                    },
                ]
            },
            {
                "title":"内存容量",
                "data":[
                    {
                        type:"16",
                        changePrice:0
                    },
                    {
                        type:"64",
                        changePrice:40
                    },
                    {
                        type:"128",
                        changePrice:60
                    },
                    {
                        type:"512",
                        changePrice:60
                    },
                ]
            },
            {
                "title":"选择版本",
                "data":[
                    {
                        type:"公开",
                        changePrice:0
                    },
                    {
                        type:"移动",
                        changePrice:40
                    }
                ]
            },
            {
                "title":"购买方式",
                "data":[
                    {
                        type:"官方标配",
                        changePrice:0
                    },
                    {
                        type:"移动版",
                        changePrice:40
                    },
                    {
                        type:"电信优惠版",
                        changePrice:40
                    }
                ]
            },
        ]

    }
}